import type { Metadata } from 'next';

import { ModeSwitch } from '@/components/ui/mode-switch';

import './global.css';

import { RootProviders } from '@/providers';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <RootProviders>
          <ModeSwitch />
          {children}
        </RootProviders>
      </body>
    </html>
  );
}
